### ISSUE TITLE
关于实验数据

### ISSUE THREAD

**Issue by HariwW** [HopeCollector/clbrl#1]
能否请作者提供一份实验数据呢？我将我自己的数据输入到程序中，发现效果不好，如果作者可以提供一份您使用的数据的话，必将万分感谢！

**Comment by HopeCollector** [comment]
![image](https://github.com/HopeCollector/clbrl/assets/20982951/5f300627-fdf5-40e4-93ef-f57d37ce6ff3)


我这还有一份单线激光采集的[数据](https://drive.google.com/drive/folders/18LT3ePnCvqa7ZTKOG4ueme7AaqGf5Y5e?usp=drive_link)

让激光旋转到某个指定的角度，然后记录下设备静止时激光采集的点云，并把角度信息保存在标量（intensity）中，同时令采集数据的序号作为文件，把这一帧数据保存为 pcd 文件，最终保存下来的数据看起来就是 1.pcd 2.pcd 3.pcd .... n.pcd 的感觉

**Comment by LunisolarStar** [comment]
你好作者，可否留个联系方式，想交流一些问题。

**Comment by HopeCollector** [comment]
> 你好作者，可否留个联系方式，想交流一些问题。

请邮件告诉我你的联系方式，比如 微信 qq 等，我的邮箱 cmw4187@126.com

**Comment by HariwW** [comment]
你好作者，我们使用了你提供的数据，然后根据帧代号（id字段）将其进行拆分成1.pcd……然后使用calib_cmb得到的融合点云仍有问题，如下图所示：
![image](https://github.com/HopeCollector/clbrl/assets/100743263/88e4cb3c-969b-487c-8163-69004ea2e3bc)
我们想请问，上述拆分的点云数据，应该使用的是扫描坐标还是统一坐标？因为我们发现你提供的数据使用了统一坐标（如下图），而config.yaml中设置了旋转轴，因此calib_cmb是否是需要输入的扫描坐标然后将其旋转得到统一坐标？
![image](https://github.com/HopeCollector/clbrl/assets/100743263/d955b529-3312-49ce-a93e-733b5449a405)
或者你是否可以跟我们解释以下具体的数据拆分方法呢？谢谢！如果在GitHub上交流不太方便，请问是否可以通过微信或者qq沟通？我们将我们的wx已发送到您邮箱。

**Comment by HopeCollector** [comment]
@HariwW 不好意思，我忘说这个数据是什么情况了，这个数据是 cmb 处理过的，不需要拆分成单线数据了

你们拿到这个数据后只需要分割出平面，然后继续下面的步骤就好了

**Comment by LunisolarStar** [comment]
> 能否请作者提供一份实验数据呢？我将我自己的数据输入到程序中，发现效果不好，如果作者可以提供一份您使用的数据的话，必将万分感谢！

你好，方便交流一下标定过程中遇到的问题吗？这是我的联系邮箱：534807824@qq.com
